import{a as d,S as E,i as f}from"./assets/vendor-C1DvvBV_.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();d.defaults.baseURL="https://pixabay.com/api/";const $="57891761-ce0c77f4e9f24f909df0cbbb9",m=15;async function h(e,o){return(await d.get("",{params:{key:$,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:m}})).data}const y=document.querySelector(".gallery"),g=document.querySelector(".loader"),p=document.querySelector(".load-more"),x=new E(".gallery a",{captionsData:"alt",captionDelay:250});function b(e){const o=e.map(({webformatURL:a,largeImageURL:n,tags:t,likes:r,views:i,comments:q,downloads:M})=>`<li class="gallery-item">
  <a class="gallery-link" href="${n}">
    <img class="gallery-image" src="${a}" alt="${t}" />
  </a>
  <div class="info">
    <p class="info-item"><b>Likes</b>${r}</p>
    <p class="info-item"><b>Views</b>${i}</p>
    <p class="info-item"><b>Comments</b>${q}</p>
    <p class="info-item"><b>Downloads</b>${M}</p>
  </div>
</li>`).join("");y.insertAdjacentHTML("beforeend",o),x.refresh()}function B(){y.innerHTML=""}function L(){g.classList.add("is-visible")}function w(){g.classList.remove("is-visible")}function v(){p.classList.add("is-visible")}function u(){p.classList.remove("is-visible")}const S=document.querySelector(".form"),C=document.querySelector(".load-more");let l="",s=1;S.addEventListener("submit",O);C.addEventListener("click",k);async function O(e){e.preventDefault();const o=e.target.elements["search-text"].value.trim();if(o===""){c("Please enter a search query!");return}l=o,s=1,B(),u(),L(),S.reset();try{const a=await h(l,s);if(a.hits.length===0){c("Sorry, there are no images matching your search query. Please try again!");return}b(a.hits),P(a.totalHits)}catch{c("Something went wrong. Please try again later!")}finally{w()}}async function k(){s+=1,u(),L();try{const e=await h(l,s);b(e.hits),H(),P(e.totalHits)}catch{s-=1,v(),c("Something went wrong. Please try again later!")}finally{w()}}function P(e){const o=Math.ceil(e/m);if(s>=o){u(),R("We're sorry, but you've reached the end of search results.");return}v()}function H(){const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}function c(e){f.error({message:e,position:"topRight",maxWidth:432,theme:"dark",backgroundColor:"#ef4040",messageColor:"#fff"})}function R(e){f.info({message:e,position:"topRight",maxWidth:432,theme:"dark",backgroundColor:"#4e75ff",messageColor:"#fff"})}
//# sourceMappingURL=index.js.map
